version: "3"

services:

  database:
    extends:
      file: docker-compose.base.yml
      service: database

  api_gateway:
    extends:
      file: docker-compose.base.yml
      service: api_gateway

  manager_api_gateway:
    extends:
      file: docker-compose.base.yml
      service: manager_api_gateway

  auth:
    extends:
      file: docker-compose.base.yml
      service: microservices_template
    build:
      context: "./auth"
      dockerfile: "Dockerfile"
    environment:
      SERVICE_HOST: "auth"
      SERVICE_NAME: "auth"
      SERVICE_PORT: 80
    depends_on:
      database:
        condition: service_healthy

  hello:
    extends:
      file: docker-compose.base.yml
      service: microservices_template
    build:
      context: "./hello"
      dockerfile: "Dockerfile"
    environment:
      SERVICE_HOST: "hello"
      SERVICE_NAME: "hello"
      SERVICE_PORT: 80

  user_python:
    extends:
      file: docker-compose.base.yml
      service: microservices_template
    build:
      context: "./user_python"
      dockerfile: "Dockerfile"
    environment:
      SERVICE_HOST: "user_python"
      SERVICE_NAME: "user"
      SERVICE_PORT: 80

  user_javascript:
    extends:
      file: docker-compose.base.yml
      service: microservices_template
    build:
      context: "./user_javascript"
      dockerfile: "Dockerfile"
    environment:
      SERVICE_HOST: "user_javascript"
      SERVICE_NAME: "user"
      SERVICE_PORT: 80
