version: "3"

services:

  database:
    extends:
      file: docker-compose.base.yml
      service: database
    volumes:
      - "./database/init.sh:/docker-entrypoint-initdb.d/init.sh"

  api_gateway:
    extends:
      file: docker-compose.base.yml
      service: api_gateway
    ports:
      - "8001:8001" # HTTP Admin API   
      - "8444:8444" # HTTPS Admin API   

  manager_api_gateway:
    extends:
      file: docker-compose.base.yml
      service: manager_api_gateway

  auth:
    extends:
      file: docker-compose.base.yml
      service: microservices_template
    build:
      context: "./auth"
      dockerfile: "Dockerfile"
    environment:
      SERVICE_HOST: "auth"
      SERVICE_NAME: "auth"
      SERVICE_PORT: 80
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "5000:80"

  hello:
    extends:
      file: docker-compose.base.yml
      service: microservices_template
    build:
      context: "./hello"
      dockerfile: "Dockerfile"
    environment:
      SERVICE_HOST: "hello"
      SERVICE_NAME: "hello"
      SERVICE_PORT: 80
    ports:
      - "5001:80"

  user_python:
    extends:
      file: docker-compose.base.yml
      service: microservices_template
    build:
      context: "./user_python"
      dockerfile: "Dockerfile"
    environment:
      SERVICE_HOST: "user_python"
      SERVICE_NAME: "user"
      SERVICE_PORT: 80
    ports:
      - "5002:80"

  user_javascript:
    extends:
      file: docker-compose.base.yml
      service: microservices_template
    build:
      context: "./user_javascript"
      dockerfile: "Dockerfile"
    environment:
      SERVICE_HOST: "user_javascript"
      SERVICE_NAME: "user"
      SERVICE_PORT: 80
    ports:
      - "5003:80"
